spring:
  application:
    name: cardapio-escolar

  datasource:
    url: jdbc:postgresql://localhost:5432/cardapio_digital
    username: gustavo
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

admin:
  username: diretora
  password: cadastro123